name:                graph-random-walks
version:             0.1.0.0
github:              "enlambdment/graph-random-walks"
license:             BSD3
author:              "JLP"
maintainer:          "JLP"
copyright:           "2020 JLP"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/enlambdment/graph-random-walks#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  graph-random-walks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graph-random-walks
